{{- if and .Values.rbac.create .Values.rbac.podSecurityPolicyEnabled }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: Role
metadata:
  name: {{ template "az-promitor-agent-resource-discovery.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "az-promitor-agent-resource-discovery.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ template "az-promitor-agent-resource-discovery.name" . }}
    verbs:
    - use
{{- end -}}
